test_file=open('my_file.txt', 'r')
text=test_file.read()
print(text)
print("==========================")
test_file=open('my_file.txt', 'a')
test_file.write("\nABCDEF")
test_file.close()
test_file=open('my_file.txt', 'r')
text=test_file.read()
print(text)
